mean 
median 
Mmode

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
m = np.random.randint(7,10,20)

In [3]:
print(m)

[9 7 9 8 8 7 7 8 7 8 8 7 8 9 9 8 9 7 8 8]


###Mean


In [5]:
np.mean(m)

7.95

# Median 

In [6]:
np.median(m)

8.0

# Mode 

In [7]:
from statistics import mode
mode(m)

8

# Population 

In [13]:
population = np.random.randint(10,20,100)

In [14]:
population


array([10, 10, 10, 13, 17, 18, 11, 15, 15, 12, 18, 13, 12, 13, 14, 18, 11,
       19, 16, 10, 19, 12, 12, 15, 19, 11, 19, 15, 17, 10, 15, 10, 18, 12,
       19, 16, 18, 13, 14, 18, 12, 13, 16, 18, 11, 10, 19, 17, 15, 15, 10,
       18, 18, 19, 13, 18, 14, 11, 10, 17, 19, 18, 16, 12, 11, 18, 14, 15,
       16, 18, 15, 17, 14, 14, 12, 19, 17, 13, 14, 18, 14, 15, 15, 18, 14,
       14, 14, 15, 15, 11, 10, 12, 19, 13, 10, 13, 15, 18, 14, 18])

In [10]:
np.mean(population)

14.78

In [11]:
np.median(population)

15.0

In [15]:
from statistics import mode
mode(population)

18

# Sample

In [16]:
sample = np.random.choice(population,20)

In [17]:
sample

array([19, 15, 11, 13, 15, 18, 14, 17, 11, 15, 18, 11, 15, 19, 12, 18, 14,
       14, 19, 10])

In [18]:
np.mean(sample)

14.9

In [19]:
np.median(sample)

15.0

In [20]:
from statistics import mode
mode(sample)

15

In [22]:
sample_1 = np.random.choice(population, 15)
sample_2 = np.random.choice(population, 15)
sample_3 = np.random.choice(population, 15)
sample_4 = np.random.choice(population, 15)

In [25]:
all_samples = [sample_1, sample_2, sample_3,sample_4]
sample_mean = []

for i in all_samples:
    sample_mean.append(np.mean(i))
    
sample_mean

[14.4, 13.6, 14.8, 14.2]

In [26]:
np.mean(sample_mean)

14.25

In [27]:
np.mean(population)

14.68