Range
Quartile
varience 
standard deviation 

In [1]:
import numpy as np

In [3]:
n = np.random.randn(9)
n

array([ 0.27215758, -0.12414098,  0.47037072, -0.83250359,  0.43002195,
        1.40988278, -0.3741888 ,  1.06683678,  0.41310966])

# Range

In [5]:
Range = np.max(n) - np.min(n)
Range

2.2423863730875286

# Quartile 

In [7]:
Q1 = np.percentile(n,25)

In [8]:
Q2 = np.percentile(n,50)


In [9]:
Q3 = np.percentile(n,75)

Interquartile Range

IQR = Third quartile - First quartile

In [12]:
IQR = Q3 - Q1
IQR

0.0

# Varience 

In [13]:
population = np.random.randn(100)
population

array([ 1.50311945,  0.62981321, -0.33437274,  1.51180693,  0.97247455,
       -0.98240278,  0.54719628, -0.04146552,  0.06311627,  0.72584158,
        0.13653002, -2.44518355, -0.5350364 ,  0.90183593, -0.0333239 ,
        0.02197341,  0.85581842,  0.86888063,  0.58394534, -0.94885571,
       -1.38726396, -0.65496584, -1.50154158,  0.01598231, -0.25926053,
       -0.40350091,  0.80936612, -1.16694565,  0.38446154, -0.21258682,
       -0.91792504,  2.60644627,  1.60751149, -0.55965684, -0.77397013,
       -1.49153877,  0.20438382, -0.77090145, -0.92917267,  1.49736015,
        1.06382725,  0.49043285,  0.42338385,  0.24232002,  1.86639015,
        0.89944945, -1.25184715, -1.5015341 , -1.85503037, -0.84601577,
        1.32298324,  0.08030045, -0.34120909, -0.30624278, -0.09165187,
        0.09069119, -1.23741529,  0.93711878, -0.95337979,  0.10046024,
        1.60436841,  0.2412627 ,  1.58663265,  0.63510019,  0.9316221 ,
        0.09788639, -1.82321672,  1.5086788 ,  1.14453673, -0.40

In [14]:
sample = np.random.choice(population, 20)
sample

array([ 0.54243005, -0.30624278,  0.09069119,  0.48839113,  1.06382725,
        0.10046024, -0.0333239 , -0.04146552,  0.80936612, -0.09165187,
        0.90183593, -0.93214779,  0.93711878,  0.93711878,  1.86639015,
        1.06382725, -0.09291237,  0.89944945,  0.06311627, -0.09165187])

In [15]:
np.var(population)

1.208978716226923

In [16]:
np.var(sample)

0.3992710572331183

# Standard Deviation 

In [17]:
np.std(population)

1.0995356821071898

In [18]:
np.std(sample)

0.6318789893904673